### ISSUE TITLE
`liferay extension mkcert` and `liferay extension mkcert --install` do not work

### ISSUE THREAD

**Issue by jotchon** [liferay/liferay-cli#103]
When generating local certificates, the instructions call for using commands `liferay extension mkcert` and `liferay extension mkcert --install`.  These command do not work, but if you replace `extension` with `runtime`, it does.  This should corrected in the file below:

https://github.com/liferay/liferay-cli/blob/9cfe49df9314931658d1a8f618b6e83e7b6f5580/docs/GETTING_STARTED.markdown?plain=1#L18

**Comment by gamerson** [comment]
Thanks @jotchon for the report,  we fixed the issue here: https://github.com/liferay/liferay-cli/pull/100 and will be merged in next release.
