### ISSUE TITLE
`liferay ext build` does not seem to respect -d parameter

### ISSUE THREAD

**Issue by allen-ziegenfus** [liferay/liferay-cli#115]
I was trying to build a directory of client extensions different from the one specified in `liferay config` by doing the following: 

```liferay ext build -d /home/allenz/liferay/liferay-portal/workspaces/liferay-dot-com-workspace/client-extensions/```

When I do that, it confirms the build directory in the output, but  it doesn't actually build the extensions in the directory I configured

**Comment by gamerson** [comment]
hey @allen-ziegenfus  i can't seem to reproduce this on my machine.  maybe we can look at this tomorrow in our call.

**Comment by allen-ziegenfus** [comment]
ok it's not so important - i have done it a different way now.
