### ISSUE TITLE
detect docker socket

### ISSUE THREAD

**Issue by rotty3000** [liferay/liferay-cli#13]
we should do two things:
* detect the socket starting with the user-centric one(s), and then iterate outward until we find one
* store the value in (viper) config in-case we choose wrongly to allow user to specify one (as a fallback)

**Comment by rotty3000** [comment]
setting `"DOCKER_HOST"` makes docker fail on windows

**Comment by gamerson** [comment]
:( we have some work to do i guess

**Comment by gamerson** [comment]
Related discussion on docker-for-mac issues page: https://github.com/docker/for-mac/issues/6545

**Comment by rotty3000** [comment]
we may have to review this in the future based on what docker desktop ends up doing.
