### ISSUE TITLE
Verbose level improvements

### ISSUE THREAD

**Issue by gamerson** [liferay/liferay-cli#42]
[ ] Move current verbose to section level of verbose (-vv)
[ ] Move git sync and docker image build output to a first level of verbose (-v)
[ ] add support for Tilt --debug so that when -vv is set, tilt also gets --debug

**Comment by rotty3000** [comment]
add support for Tilt `--debug` so that when `-vv` is set, tilt also gets `--debug`

**Comment by rotty3000** [comment]
See https://issues.liferay.com/browse/LXC-168
