### ISSUE TITLE
automatically detect (tilt refresh) new client extensions

### ISSUE THREAD

**Issue by rotty3000** [liferay/liferay-cli#81]
I'm thinking of `inotify`.

**Comment by rotty3000** [comment]
Merge into next at https://github.com/liferay/liferay-localdev/commit/d9139551c39a349b2b3ed5c5e1be36aea892f115

**Comment by gamerson** [comment]
Hey Ray I'm running the latest CLI from `next` and latest localdev synced from `next` and I'm getting an error that I posted over on localdev repo PR
https://github.com/liferay/liferay-localdev/pull/83#issuecomment-1304612154

**Comment by gamerson** [comment]
The problem I found is not due to this new feature, it turns out the updated localdev image was not actually building, see #93  Remarking this issue as closed.
