### ISSUE TITLE
consider combining `extension mkcert` and `extension mkcert --install` into one command

### ISSUE THREAD

**Issue by gamerson** [liferay/liferay-cli#88]
Right now devs have to do `liferay extension mkcert` and `liferay extension mkcert --install` as two separate commands.

I think that `lifery extension mkcert --install` should do both.  

However, we do want to support `liferay extension mkcert` as only generating the wildcard cert.  Because the dev may want ot change the `LFRDEV_DOMAIN` and generate different wildcard certs.

**Comment by rotty3000** [comment]
See https://issues.liferay.com/browse/LXC-170
