### ISSUE TITLE
liferay-cli will use a previously built localdev image, leading to errors

### ISSUE THREAD

**Issue by gamerson** [liferay/liferay-cli#93]
As I was looking into errors found with latest localdev PR https://github.com/liferay/liferay-localdev/pull/83, I found that the latest localdev `next` image fails to build.  As it turns out,  if CLI fails to build new localdev image, it will fall back to using previously built localdev image.  

I cleared all my image ccaches and my localdev-server tags and then I re-ran a command I got this error
```Step 18/29 : RUN     groupmod -g $DOCKER_GID docker &&     groupadd -g $GID -o $UNAME &&     useradd -d /home/$UNAME -g $GID -m -s /bin/bash -u $UID $UNAME &&     mkdir /workspace &&     chown $UNAME:$UNAME /workspace
 ---> Running in eb6200041fdc
groupmod: GID '20' already exists
2022/11/05 16:11:45 Failed to create container localdev-status: Error response from daemon: No such image: localdev-server:latest```

So the issue with CLI is that it does not fail the CLI command if the localdev-image fails to build.

**Comment by rotty3000** [comment]
See https://issues.liferay.com/browse/LXC-157
