### ISSUE TITLE
extension command not supported (or listed) for liferay command

### ISSUE THREAD

**Issue by andrewatliferay** [liferay/liferay-cli#99]
I'm trying this out on my Linux laptop which is running Ubuntu 20. I'm trying to follow the guide which has the following instructions. 

- [ ] Execute liferay extension mkcert (this will generate a wildcard certificate for *.lfr.dev)
- [ ] 
- [ ] Execute liferay extension mkcert --install (This will install the rootCA that you just generated into your OS keystores, or Chrome/Firefox/Edge keystores)

... but when I run the command, neither works for me. In both cases I get the usage output with the following showing for the available commands.

Available Commands:
  build       Executes the client extension workspace build to generate deployable artifacts (zip files)
  create      Creates new Client Extensions using a wizard-like interface
  refresh     Refreshes client-extension workload resources in localdev server
  start       Starts all client-extension workloads
  status      Returns the status of the extension environment
  stop        Stops all client-extension workloads

**Comment by gamerson** [comment]
Typo! Thanks for report. It should be `liferay runtime mkcert` and `liferay runtime mkcert --install`
